---
name: "Registry Image Update Checker"
description: "GitHub Action to check if the base container image that your image is based on was updated and your image needs to be updated"
author: Georg Jung <github-actions@gjung.com>

inputs:
  base-image:
    description: "Container base image. E.g. nginx, nginx:latest, ghcr.io/greatorg/greatapp:latest"
    required: true
  image:
    description: "Container image. E.g. nginx, nginx:latest, ghcr.io/greatorg/greatapp:latest. Can point to a different registry than base-image does."
    required: true
  os:
    description: "OS being used, will default to the OS running the action."
    required: false
    default: ""
  arch:
    description: "Architecture of the image, used for multiarch images. Like amd64 or arm64. Will default to the OS architecture running the action (limited support)."
    required: false
    default: ""
  verbose:
    description: "Show verbose output"
    required: false
    default: "false"
  github_token:
    description: "Github Token to authenticate against ghcr.io, if image or base-image is a private ghcr image."
    required: false
    default: ""
outputs:
  needs-updating:
    description: "true or false, true if the image needs updating (does not match the base image), false if it does not need updating"
    value: ${{ steps.run-script.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: run-script
      run: |
        OUTPUT=`FULL_BASE=${{ inputs.base-image }} FULL_IMAGE=${{ inputs.image }} OS=${{ inputs.os }} ARCH=${{ inputs.arch }} VERBOSE=${{ inputs.verbose }} GITHUB_TOKEN=${{ inputs.github_token }} $GITHUB_ACTION_PATH/docker.sh`
        if [ "$?" != "0" ]; then
          >&2 echo "Error running update checker action."
          exit 1
        fi
        if [ "${{ inputs.verbose }}" == "true" ]; then
          echo "`head -n -1 <<< $OUTPUT`"
          OUTPUT=`tail -n1 <<< $OUTPUT`
          echo needs-updating: $OUTPUT
        fi
        echo "result=$OUTPUT" >> $GITHUB_OUTPUT
      shell: bash

branding:
  icon: refresh-cw
  color: blue
